[BugFix] Pagination and Serial number column issue is fixed
Yojak-Tech/react-table-component pull request #7
Opened 2021-12-09 10:21 UTC by prateek-yojak

Pagination is working now and serial number column is also working. You have to write keyName='sno' to get serial number.

2021-12-10 11:37 UTC, lakshita-yojak requested changes

2021-12-10 11:37 UTC, lakshita-yojak commented on src/table/Table.tsx
> +import './table.css';
put this at end of external file

2021-12-10 11:37 UTC, lakshita-yojak commented on src/table/Table.tsx
> +	handleRowClick= null
add space before =

2021-12-10 11:37 UTC, lakshita-yojak commented on src/table/TableRow.tsx
> +								else if (typeof result[keyMain]==="boolean" || result[keyMain]===0){
use !result[keyMain] instead of result[keyMain]===0

2021-12-10 11:37 UTC, lakshita-yojak commented on src/table/TableRow.tsx
> +								result = keyMain in result ? result[keyMain] : index+1;}
add space after paranthesis

2021-12-13 09:34 UTC, Tushar19varshney commented
Please squash this PR.

2021-12-16 13:13 UTC, Tushar19varshney commented
Great work @prateek-yojak 👍

2021-12-16 13:13 UTC, merged